HelpMe/HelpMe/Models/TypeCustomViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HelpMe.Models
{
    /// <summary>
    /// Тип задачи
    /// </summary>
    public class TypeCustomViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public ICollection<CustomViewModel> Customs { get; set; }

        public TypeCustomViewModel()
        {
            Customs = new List<CustomViewModel>();
        }
    }
}

HelpMe/HelpMe/Controllers/TypeCustomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HelpMe.Models;
using System.IO;

namespace HelpMe.Controllers
{
    public class TypeCustomController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TypeCustom
        public async Task<ActionResult> Index()
        {
            return View(await db.CustomTypes.ToListAsync());
        }

        // GET: TypeCustom/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeCustomViewModel typeCustomViewModel = await db.CustomTypes.FindAsync(id);
            if (typeCustomViewModel == null)
            {
                return HttpNotFound();
            }
            return View(typeCustomViewModel);
        }

        // GET: TypeCustom/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeCustom/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult>
            Create([Bind(Include = "Id,Name,ImagePath,ImageFile")] TypeCustomViewModel typeTaskViewModel)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileName(typeTaskViewModel.ImageFile.FileName);
                string path = Server.MapPath("~/Files/" + fileName);
                // сохраняем файл в папку Files в проекте
                typeTaskViewModel.ImageFile.SaveAs(path);
                typeTaskViewModel.ImagePath = "~/Files/" + fileName;
                db.CustomTypes.Add(typeTaskViewModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(typeTaskViewModel);
        }


        // GET: TypeCustom/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeCustomViewModel typeCustomViewModel = await db.CustomTypes.FindAsync(id);
            if (typeCustomViewModel == null)
            {
                return HttpNotFound();
            }
            return View(typeCustomViewModel);
        }

        // POST: TypeCustom/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,ImagePath")] TypeCustomViewModel typeCustomViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeCustomViewModel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(typeCustomViewModel);
        }

        // GET: TypeCustom/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeCustomViewModel typeCustomViewModel = await db.CustomTypes.FindAsync(id);
            if (typeCustomViewModel == null)
            {
                return HttpNotFound();
            }
            return View(typeCustomViewModel);
        }

        // POST: TypeCustom/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TypeCustomViewModel typeCustomViewModel = await db.CustomTypes.FindAsync(id);
            db.CustomTypes.Remove(typeCustomViewModel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HelpMe/HelpMe/Views/TypeCustom/Create.cshtml
@model HelpMe.Models.TypeCustomViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "TypeCustom", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TypeTaskViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HelpMe/HelpMe/Views/TypeCustom/Delete.cshtml
@model HelpMe.Models.TypeCustomViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TypeCustomViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HelpMe/HelpMe/Views/TypeCustom/Details.cshtml
@model HelpMe.Models.TypeCustomViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TypeCustomViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HelpMe/HelpMe/Views/TypeCustom/Edit.cshtml
@model HelpMe.Models.TypeCustomViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TypeCustomViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HelpMe/HelpMe/Views/TypeCustom/Index.cshtml
@model IEnumerable<HelpMe.Models.TypeCustomViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>