HelpMe/HelpMe/Models/CustomViewModel.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Web;

namespace HelpMe.Models
{
    /// <summary>
    /// класс заказов
    /// </summary>
    [System.Runtime.Serialization.KnownType(typeof(UserViewModel))]
    [System.Runtime.Serialization.KnownType(typeof(User))]
    [System.Runtime.Serialization.KnownType(typeof(IdentityUser))]
    public class CustomViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public CustomStatus Status { get; set; }
        public bool? DoneInTime { get; set; }
        public string FilePath { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndingDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ExecutorStartDate { get; set; }
        public int? TypeTaskId { get; set; }
        public TypeCustomViewModel TypeTask { get; set; }
        public int? CategoryTaskId { get; set; }
        public TaskCategory CategoryTask { get; set; }
        public int? SkillId { get; set; }
        public Skill Skill { get; set; }
        public int? Price { get; set; }
        public int TimeBlock { get; set; }
        public int? PlagiarismPercentage { get; set; }
        public string AttachFilePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase AttachFile { get; set; }

        public string UserId { get; set; }
        public virtual User User { get; set; }

        public string ExecutorId { get; set; }
        [ForeignKey("ExecutorId")]
        public virtual User Executor { get; set; }

        public int ExecutorPrice { get; set; }

        public bool IsRevision { get; set; }

        public ICollection<CommentViewModel> Comments { get; set; }
        public ICollection<AttachModel> Attachments { get; set; }
        public ICollection<MyAttachModel> MyAttachments { get; set; }
        public ICollection<MainAttachModel> MainAttachments { get; set; }

        [NotMapped]
        public TimeSpan? TotalHrs
        {
            get
            { 
                return EndingDate - DateTime.Now;
            }
        }

        public CustomViewModel()
        {
            Comments = new List<CommentViewModel>();
            Attachments = new List<AttachModel>();
            MyAttachments = new List<MyAttachModel>();
            MainAttachments = new List<MainAttachModel>();
        } 
    }

    public class MainAttachModel
    {
        public int Id { get; set; }
        public int? CustomViewModelId { get; set; }
        public CustomViewModel CustomViewModel { get; set; }
        public string UserId { get; set; }
        public virtual User User { get; set; }
        public bool IsDownloaded { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DownloadDate { get; set; }
        public string AttachFileName { get; set; }
        public string AttachFileExtens { get; set; }
        public string AttachFilePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase AttachFile { get; set; }
        public AttachStatus AttachStatus { get; set; }
    }


    public class MyAttachModel
    {
        public int Id { get; set; }
        public int? CustomViewModelId { get; set; }
        public CustomViewModel CustomViewModel { get; set; }
        public string UserId { get; set; }
        public virtual User User { get; set; }
        public string AttachFileName { get; set; }
        public string AttachFileExtens { get; set; }
        public string AttachFilePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase AttachFile { get; set; }
        public AttachStatus AttachStatus { get; set; }
    }

    public class AttachModel
    {
        public int Id { get; set; }
        public int ExecutorPrice { get; set; }
        public int? CustomViewModelId { get; set; }
        public bool IsRevision { get; set; }
        public CustomViewModel CustomViewModel { get; set; }
        public string UserId { get; set; }
        public virtual User User { get; set; }
        public string AttachFileName { get; set; }
        public string AttachFileExtens { get; set; }
        public string AttachFilePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase AttachFile { get; set; }
        public AttachStatus AttachStatus { get; set; }
    }

    public class PageInfo
    {
        public int PageNumber { get; set; } // номер текущей страницы
        public int PageSize { get; set; } // кол-во объектов на странице
        public int TotalItems { get; set; } // всего объектов
        public int TotalPages  // всего страниц
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / PageSize); }
        }

        public bool HasPreviousPage { get { return PageNumber > 1 && TotalPages > 1; } }
        public int PreviousPageIndex { get { return PageNumber - 1; } }
        public bool HasNextPage { get { return PageNumber < TotalPages && TotalPages > 1; } }
        public int NextPageIndex { get { return PageNumber + 1; } }
    }
    public class CustomIndexViewModel
    {
        public IEnumerable<CustomViewModel> Customs { get; set; }
        public PageInfo PageInfo { get; set; }
    }

    public enum AttachStatus
    {
        [Display(Name = "Работа куплена")]
        Purchased,
        [Display(Name = "Не куплена")]
        NotPurchased
    }


    public enum CustomStatus
    {
        [Display(Name = "Открытая заявка")]
        Open,
        [Display(Name = "Закрытая заявка")]
        Close,
        [Display(Name = "Выполняется исполнителем")]
        Check,
        [Display(Name = "Ожидает покупки")]
        NeedBuy,
        [Display(Name = "Проверяется заказчиком")]
        CheckCustom,
        [Display(Name = "На доработке")]
        Revision,
        [Display(Name = "Отменён")]
        Cancelled
    }

  

}

HelpMe/HelpMe/Controllers/CustomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HelpMe.Models;
using Microsoft.AspNet.Identity;
using HelpMe.Hubs;
using System.IO;
using ICSharpCode.SharpZipLib.Zip;
using ICSharpCode.SharpZipLib.Core;
using HelpMe.Helpers;

namespace HelpMe.Controllers
{
    public class CustomController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        int pageSize = 15; // количество объектов на страницу

        // GET: Custom
        public ActionResult Index(int? id, string name, int? typeTaskId, int? taskCategoryId, int? skillId,
            int? minPrice, int? maxPrice, bool? customsWithoutOffers, int sortId = 1)
        {
            //подгружаем только открытые заявки
            var customViewModels = db.Customs/*.Where(c=>c.Status==CustomStatus.Open)*/.Include(c => c.Comments).Include(c => c.User)
                .Include(c => c.TypeTask).Include(c => c.CategoryTask).Include(c => c.Skill);
            //var count = customViewModels.Count();

            if (!String.IsNullOrEmpty(name))
            {
                customViewModels = customViewModels.Where(m => m.Name.Contains(name));
            }
            //count = customViewModels.Count();

            if (taskCategoryId != null && taskCategoryId != 0)
            {
                customViewModels = customViewModels.Where(m => m.CategoryTaskId == taskCategoryId);

                if (skillId != null && skillId != 0)
                {
                    customViewModels = customViewModels.Where(m => m.SkillId == skillId);
                }
            }
            //count = customViewModels.Count();

            if (minPrice != null && minPrice != 0)
            {
                customViewModels = customViewModels.Where(m => m.Price >= minPrice || m.Price == null);
            }
            //count = customViewModels.Count();

            if (maxPrice != null)
            {
                customViewModels = customViewModels.Where(m => (m.Price == null || m.Price <= maxPrice));
            }
            //count = customViewModels.Count();

            if (customsWithoutOffers == true)
            {
                customViewModels = customViewModels.Where(m => m.Comments.Count == 0);
            }
            //count = customViewModels.Count();

            customViewModels = SortCustoms(customViewModels, sortId);

            int page = id ?? 0;
            //IEnumerable<CustomViewModel> customPerPages = customViewModels.Skip((page - 1) * pageSize).Take(pageSize);
            //PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = customViewModels.Count() };


            //CustomIndexViewModel ivm = new CustomIndexViewModel { PageInfo = pageInfo, Customs = customPerPages };

            //count = customViewModels.Count();

            ViewBag.Tasks = new SelectList(db.TaskCategories, "Id", "Name");
            TempData["CustomsFound"] = customViewModels.Count();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_CustomsPage", GetCustomsPage(customViewModels, page));
            }

            return View(GetCustomsPage(customViewModels, page));
        }

        private IEnumerable<CustomViewModel> GetCustomsPage(IQueryable<CustomViewModel> customs, int page)
        {

            var customsToSkip = page * pageSize;
            var customsToPage = customs.Skip(customsToSkip).Take(pageSize);
            return customsToPage.ToList();
        }

        public IQueryable<CustomViewModel> SortCustoms(IQueryable<CustomViewModel> customs, int sortId)
        {
            //by new customs
            if (sortId == 1)
            {
                customs = customs.OrderByDescending(m => m.StartDate);
            }
            //by old customs
            if (sortId == 2)
            {
                customs = customs.OrderBy(m => m.StartDate);
            }
            //by price descending
            if (sortId == 3)
            {
                customs = customs.OrderByDescending(m => m.Price);
            }
            //by price ascending
            if (sortId == 4)
            {
                customs = customs.OrderBy(m => m.Price);
            }

            return customs;
        }

        public int GetCustomsCount()
        {
            return (int)TempData["CustomsFound"];
        }


        [Authorize(Roles = "User")]
        public ActionResult Tasks()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.UnreadingCount = db.Messages.Where(m => m.UserToId == userId && m.Status == MessageStatus.Undreading).Count();

            var tasksModel = db.Customs.Include(c => c.TypeTask)
                .Include(c => c.CategoryTask)
                //.Include(c => c.Executor)
                .Include(c => c.Skill)
                .Include(c => c.User)
                .Include(c => c.MyAttachments)
                .Include(c => c.Comments)
                .Where(t => t.UserId == userId).OrderByDescending(m => m.Id).ToList();
            return View(tasksModel);
        }

        [Authorize(Roles = "employee")]
        public ActionResult TasksExec()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.UnreadingCount = db.Messages.Where(m => m.UserToId == userId && m.Status == MessageStatus.Undreading).Count();

            var tasksModel = db.Customs.Include(c => c.TypeTask)
                .Include(c => c.CategoryTask)
                .Include(c => c.Executor)
                .Include(c => c.Skill)
                .Include(c => c.User).Include(c => c.MyAttachments)
                   .Include(c => c.Comments)
                .Where(t => t.ExecutorId == userId).ToList();

            return View(tasksModel);
        }

        [Authorize(Roles = "User")]
        public ActionResult Bidders(int? id)
        {
            var customViewModels = db.Customs.Include(c => c.Comments)
                                            .Include(c => c.User)
                                            //.Include(c => c.Executor)
                                            .Where(i => i.Id == id).FirstOrDefault();

            var comms = customViewModels.Comments.ToList();

            string userId = User.Identity.GetUserId();
            ViewBag.UnreadingCount = db.Messages.Where(m => m.UserToId == userId && m.Status == MessageStatus.Undreading).Count();

            return View(comms);
        }


        [Authorize(Roles = "employee")]
        public ActionResult MyActiveBids()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.UnreadingCount = db.Messages.Where(m => m.UserToId == userId && m.Status == MessageStatus.Undreading).Count();

            var comms = db.Comments.Include(u => u.User).Include(u => u.CustomViewModel).Where(u => u.UserId == userId);

            return View(comms);
        }

        public async Task<string> GetCustomStatus(int? id)
        {
            var status = await db.Customs.Where(c => c.Id == id).Select(c => c.Status).FirstOrDefaultAsync();
            return status.GetDisplayName();
        }

        public ActionResult LoadMyAttaches(int? id)
        {
            var allAttaches = db.MyAttachments.Include(c => c.CustomViewModel).Where(c => c.CustomViewModelId == id).ToList();
            return PartialView(allAttaches);
        }

        public ActionResult LoadMainAttaches(int? id)
        {
            var allMainAttaches = db.MainAttachments.Include(m => m.CustomViewModel).Where(c => c.CustomViewModelId == id).ToList();
            return PartialView(allMainAttaches);
        }

        public ActionResult LoadAttaches(int? id)
        {
            var allAttaches = db.Attachments.Include(c => c.CustomViewModel).Where(c => c.CustomViewModelId == id).ToList();
            return PartialView(allAttaches);
        }

        public ActionResult LoadButtons(int? id)
        {
            var customViewModel = db.Customs.Where(c => c.Id == id).SingleOrDefault();
            return PartialView(customViewModel);
        }

        public ActionResult LoadButtonArch(int? id)
        {
            var customViewModel = db.Customs.Where(c => c.Id == id).SingleOrDefault();
            return PartialView(customViewModel);
        }

        public async Task<int> NotDownloadedMainAttaches(int? id)
        {
            var custom = await db.Customs.FirstOrDefaultAsync(c => c.Id == id);
            var count = await db.MainAttachments.Where(a => a.CustomViewModelId == id).CountAsync(m => m.IsDownloaded == false);
            if (count == 0)
            {
                custom.Status = CustomStatus.CheckCustom;
                db.Entry(custom).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return count;
        }

        public async Task<int> NotPurchasedAttaches(int? id)
        {
            return await db.Attachments.Where(a => a.CustomViewModelId == id).CountAsync(a => a.AttachStatus == AttachStatus.NotPurchased);
        }


        [HttpPost]
        [Authorize(Roles = "employee")]
        //удаление готового решения (исполнителем)
        public async Task<JsonResult> DeleteMainAttach(int? id)
        {
            var mainAttach = await db.MainAttachments.FindAsync(id);
            var customId = mainAttach.CustomViewModelId;
            var customViewModel = await db.Customs.Include(c => c.MainAttachments).FirstOrDefaultAsync(c => c.Id == customId);
            db.MainAttachments.Remove(mainAttach);
            var mainAttachments = customViewModel.MainAttachments;

            if (mainAttachments.Where(m => m.IsDownloaded == true).Count() == 0)
            {
                db.Entry(customViewModel).State = EntityState.Modified;

HelpMe/HelpMe/Views/Custom/CustomSearch.cshtml
@model IEnumerable<HelpMe.Models.CustomViewModel>

@foreach (var item in Model)
{
    <!-- Task -->
    <a href=@Url.Action("Details", new { id = item.Id }) class="task-listing">

        <!-- Job Listing Details -->
        <div class="task-listing-details">

            <!-- Details -->
            <div class="task-listing-description">
                <h3 class="task-listing-title"> @Html.DisplayFor(modelItem => item.Name)</h3>
                <ul class="task-icons">
                    <li><i class="icon-material-outline-location-on"></i> San Francisco</li>
                    <li><i class="icon-material-outline-access-time"></i> 2 minutes ago</li>
                </ul>
            </div>

        </div>

        <div class="task-listing-bid">
            <div class="task-listing-bid-inner">
                <div class="task-offers">
                    <strong>$1,000 - $2,500</strong>
                    <span>Fixed Price</span>
                </div>

            </div>
        </div>
    </a>

}

HelpMe/HelpMe/Views/Custom/Delete.cshtml
@model HelpMe.Models.CustomViewModel

@{
    ViewBag.Title = "Удаление заказа";
}

<h2>Delete</h2>

<h3>Вы уверены, что хотите удалить заказ?</h3>
<div>
    <h4>Удаление</h4>
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            Название заказа
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Описание заказа
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К общему списку", "Index")
        </div>
    }
</div>

HelpMe/HelpMe/Views/Custom/LoadAttaches.cshtml
@using HelpMe.Helpers
@using Microsoft.AspNet.Identity
@model IEnumerable<HelpMe.Models.AttachModel>

<div class="attachments-container">
    @{ var idnew = 1; }
    @foreach (var i in Model)
    {
    <div style="margin-bottom:20px; margin-right:16px">
        <a style='@(i.AttachStatus == HelpMe.Models.AttachStatus.NotPurchased && i.CustomViewModel.ExecutorId != User.Identity.GetUserId() ? "pointer-events: none;" : "")'
           href="@Url.Action("GetFileAttach", "Custom", new { path = i.AttachFilePath, id = i.Id })"
           class="attachment-box ripple-effect "><span style="width:152px">@i.AttachFileName</span><i style="margin-left:40px">@i.ExecutorPrice руб.</i><i style="">@i.AttachFileExtens.TrimStart('.')</i></a>
        @if (i.CustomViewModel.ExecutorId == User.Identity.GetUserId() && i.AttachStatus == HelpMe.Models.AttachStatus.NotPurchased)
        {
            @Ajax.RawActionLink("<i id='fDelbuy"+@i.Id+"' class='icon-feather-trash-2'></i><div id='ldsDelAttach" + i.Id + "' style='display:none' class='lds-ring'><div></div><div></div><div></div><div></div></div>", "DeleteAttach","Custom",
           new{ id = i.Id},
           new AjaxOptions{ OnBegin = "return ConfirmDone()", HttpMethod = "POST", OnSuccess = "OnSuccessDeleteAttach('" + @i.Id + "')" },
           new {
               id ="delete-attach",
               @class = "button green ripple-effect ico",
               @style = "padding: 3px 5px 3px 3px; ",
               title = "Удалить решение",
               data_tippy_placement = "top"
           }
           )
            @*@Ajax.RawActionLink("<i id='fDelbuy"+@i.Id+"' class='icon-feather-edit'></i><div id='ldsDelAttach" + i.Id + "' style='display:none' class='lds-ring'><div></div><div></div><div></div><div></div></div>", "DeleteAttach","Custom",
          new{ id = i.Id},
          new AjaxOptions{ OnBegin = "return ConfirmDone()", HttpMethod = "POST", OnSuccess = "OnSuccessDeleteAttach('" + @i.Id + "')" },
          new {
              id ="delete-attach",
              @class = "button green ripple-effect ico",
              @style = "margin-left:5px; padding: 3px 5px 3px 3px; ",
              title = "Удалить решение",
              data_tippy_placement = "top"
          }
          )*@
        }
        @if (i.CustomViewModel.UserId == User.Identity.GetUserId())
        {
            if (i.AttachStatus == HelpMe.Models.AttachStatus.NotPurchased)
            {
                @Ajax.RawActionLink(
               "<i id='fbuy' style='margin-top: -10px;' class='icon-material-outline-monetization-on'></i><span id='textAttachBuy'>Купить</span><div style = 'left:40%' class='lds-ring'><div></div><div></div><div></div><div></div></div>", "Buy", "Custom",
               new{id = i.Id},
               new AjaxOptions{ OnBegin= "return OnBeginBuyAttach('"+@i.Id+"')", OnSuccess = "return OnSuccessBuyAttach('" + @i.Id + "')", HttpMethod = "POST" },
               new {
                   id = "buy-solution",
                   @class = "button ripple-effect",
                   @style = (i.AttachStatus == HelpMe.Models.AttachStatus.Purchased ? "display:;    margin-top: -5px;" : "    margin-top: -5px;"),
                   title = "Купить",
                   data_tippy_placement = "top"
               }
               )
            }
            else
            {
                <div style="margin-top:-10px" class="task-tags margin-bottom-20">
                    <span>Работа куплена</span>
                </div>

            }
        }
        @if (i.CustomViewModel.ExecutorId == User.Identity.GetUserId())
        {
            if (i.AttachStatus != HelpMe.Models.AttachStatus.NotPurchased)
            {
                <div style='margin-top: -10px;' class="task-tags ">
                    <span>Работа куплена</span>
                </div>
            }
        }

    </div>
        idnew = idnew + 1;
    }

</div>

<br />

HelpMe/HelpMe/Views/Custom/LoadButtonArch.cshtml
@model HelpMe.Models.CustomViewModel
@using Microsoft.AspNet.Identity

@if (Model.UserId == User.Identity.GetUserId())
{

    <a style="margin-bottom:20px" id="getArch"
       class="button gray ripple-effect button-sliding-icon"
       href="@Url.Action("GetArchive", "Custom", new { id = Model.Id })">Скачать все архивом<i class="icon-feather-arrow-down"></i></a>

}

HelpMe/HelpMe/Views/Custom/LoadMainAttaches.cshtml
@using HelpMe.Helpers
@using Microsoft.AspNet.Identity
@model IEnumerable<HelpMe.Models.MainAttachModel>

<div class="attachments-container">

    @foreach (var i in Model)
    {
        <div style="margin-bottom:20px; margin-right:14px">
            @if (i.CustomViewModel.ExecutorId == User.Identity.GetUserId() && Request.IsAuthenticated)
            {
                <a class="attachment-box ripple-effect" href="@Url.Action("GetFile", "Custom", new { path = i.AttachFilePath })"><span style="width:152px">@i.AttachFileName</span><i>@i.AttachFileExtens.TrimStart('.')</i></a>
            }
            else
            {
                string attachPath = i.AttachFilePath.Replace("\\", "\\\\");
                <a id="download-main-by-customer" class="attachment-box ripple-effect" onclick="DownloadMainAttachmentByCustomer(@i.Id,@i.CustomViewModel.Id, '@attachPath')"><span style="width:152px">@i.AttachFileName</span><i>@i.AttachFileExtens.TrimStart('.')</i></a>
            }
            @if (i.CustomViewModel.ExecutorId == User.Identity.GetUserId() && (i.CustomViewModel.IsRevision == false && i.CustomViewModel.Status != HelpMe.Models.CustomStatus.Close))
            {
                @Ajax.RawActionLink("<i id='fDelMain" + @i.Id + "' class='icon-feather-trash-2'></i><div id='ldsDelMainAttach" + i.Id + "' style='display:none' class='lds-ring'><div></div><div></div><div></div><div></div></div>", "DeleteMainAttach", "Custom",
                        new { id = i.Id },
                        new AjaxOptions { OnBegin = "return ConfirmDone()", HttpMethod = "POST", OnSuccess = "OnSuccessDeleteMainAttach('" + @i.Id + "')" },
                        new
                        {
                            id = "delete-attach",
                            @class = "button green ripple-effect ico",
                            @style = "margin-left:5px; padding: 3px 5px 3px 3px; ",
                            title = "Удалить решение",
                            data_tippy_placement = "top"
                        }
                        )
            }

        </div>

    }
</div>
<br />

HelpMe/HelpMe/Views/Custom/LoadMyAttaches.cshtml
@using HelpMe.Helpers
@using Microsoft.AspNet.Identity


<div class="attachments-container">
    @foreach (var i in Model)
    {
        <a class="attachment-box ripple-effect" href="@Url.Action("GetFile", "Custom", new { path = i.AttachFilePath })"><span style="width:152px">@i.AttachFileName</span><i>@i.AttachFileExtens.TrimStart('.')</i></a>
    }
</div>
<br />

       

HelpMe/HelpMe/Views/Custom/_CustomsPage.cshtml
@model IEnumerable<HelpMe.Models.CustomViewModel>
@*@model HelpMe.Models.CustomIndexViewModel*@

@foreach (var item in Model)
{
    <!-- Job Listing -->
    <a href="@Url.Action("Details", new { id = item.Id })" class="job-listing" target="_blank">

        <!-- Job Listing Details -->
        <div class="job-listing-details">
            <!-- Logo -->
            <div class="job-listing-company-logo">
                <img src="~/Content/Custom/images/company-logo-01.png" title=@item.TypeTask.Name alt="Task type">
            </div>

            <!-- Details -->
            <div class="job-listing-description">
                @{ 
                    string customName = item.Name;
                    if (customName.Length >= 50)
                    {
                        customName = customName.Substring(0,47)+"...";
                    }
                }
                <h3 class="job-listing-title">@customName</h3>
                <h4 class="job-listing-company"><i class="icon-material-outline-account-circle"></i> Предложений: @Html.DisplayFor(modelItem=>item.Comments.Count) </h4>
            </div>
        </div>

        <!-- Job Listing Footer -->
        <div class="job-listing-footer">
            <span title="В избранное" class="bookmark-icon"></span>
            <ul>
                <li>
                    <i class="icon-material-outline-school"></i> @item.CategoryTask.Name @{
                        var skillName = "";
                        if (item.SkillId != null) { skillName = "- " + item.Skill.Name; }
                    }
                    @skillName
                </li>
                <li><i class="icon-material-outline-date-range"></i>Сдать до: <strong>@(item.EndingDate == null ? "Не указано" : item.EndingDate?.ToShortDateString())</strong></li>
                <li><i class="icon-material-outline-account-balance-wallet"></i> Бюджет: <strong>@(item.Price==null ? "по договоренности" : item.Price.ToString() + "руб.")</strong></li>
                <li title="Дата публикации"><i class="icon-material-outline-access-time"></i>@item.StartDate.ToShortDateString() </li>
            </ul>
        </div>
    </a>
}